### ISSUE TITLE
[BUG] Query parameters are not included in Requests

### ISSUE THREAD

**Issue by valeriomazzeo** [vapor/engine#128]
Query parameters are not included in the requests when uri doesn't have any.

- Create a request: `client.request(.get, "http://localhost", query: ["key": "value"])`

**Expected Behaviour:**
- Request query should contain `["key": "value"]`.

**Current Behaviour:**
- Request query is `nil`.

**Code involved:**

`Responder+Helpers.swift`

```swift
public func request(
        _ method: Method,
        _ uri: String,
        query: [String: NodeRepresentable] = [:],
        _ headers: [HeaderKey: String] = [:],
        _ body: BodyRepresentable? = nil,
        through middleware: [Middleware] = []
    ) throws  -> Response {
        let uri = try URI(uri)
    
        let req = Request(method: method, uri: uri)
        req.headers = headers
        
        for (key, value) in query {
            try req.query?.set(key, value)
        }
        
        if let body = body {
            req.body = body.makeBody()
        }
        return try respond(to: req, through: middleware)
    }
```

**Note:**

This works if the uri contains already a query parameter (for example: `client.request(.get, "http://localhost?foo=bar", query: ["key": "value"])`), because of the `Request` extension in:

`Request+FormURLEncoded.swift`

```swift
public var query: Node?
```

**Comment by tanner0101** [comment]
looks like we just need to make sure the `req.query` variable is not nil first.

**Comment by tanner0101** [comment]
Moving this to vapor/vapor.
