### ISSUE TITLE
Unexpected new behavior of Response(redirect:)

### ISSUE THREAD

**Issue by vzsg** [vapor/engine#133]
## Introduction

(Continuing from vapor/vapor#1018.)

#88 incorrectly assumed that the HTTP 307 status is the de facto replacement of the old 302 status code. 

Changing the code returned introduced a sneaky breaking behavioral change, making a common use case impossible without dropping down to manually creating redirect responses.

This comes down to a wrong idea: there are not just two kinds of redirects (permanent or temporary).

## Previously in Vapor 1

A very common pattern in web apps is redirecting the browser after a form POST request to a result or list page, which would be loaded using a GET request. (By using this, the chance of duplicated POST requests happening on a page refresh is close to zero.)

In V1, using `Response.redirect` in a post handler achieved exactly that.

In V2 with #88 in place, this is not readily available and migrated apps will break.

## History lesson

The industry moved from 302 because the browser's expected behavior was **not explicitly defined**. The de facto behavior eventually became that the new request uses the GET method — allowing for the forementioned pattern.

Instead, the status codes 303 and 307 allow for explicit control over the new request. 303 forces the user agent to use GET, and 307 forces it to use the original method again.

These two distinct behaviors, along with 301 — which is exposed via the `permanently` parameter — are valid choices that should all be available easily.

## Proposed solution

1. Undo #88 and make 302 (or 303) the default temporary redirect again to avoid projects breaking.
1. (Optionally) add another convenience initializer that either takes a HTTP status code, or an enum to select one of the three behaviors.

## Workaround

Manually building the redirect response works:

```swift
return Response(status: .seeOther, headers: [.location: "url"])
```

**Comment by tanner0101** [comment]
I'm thinking something like this:

```swift
enum RedirectType {
    case permanent // 301 permanent 
    case normal // 303 see other
    case retry // 307 temporary
}
```

With updated API:

```
return Response(redirect: "/foo", type: .retry)
```

And we continue deprecated support for the old API, switching to `.normal` to recreate the old behavior.

**Comment by vzsg** [comment]
Yes, that would bevnice for the enhancement part. But perhaps a point release could revert the default code even before that? 🤔

**Comment by tanner0101** [comment]
I think that's a good idea. This is on my todo list, but feel free to submit a PR if you'd like.
