### ISSUE TITLE
Headers should be lowercase

### ISSUE THREAD

**Issue by 0xTim** [vapor/engine#134]
As per the [HTTP 2.0 spec](https://tools.ietf.org/html/draft-ietf-httpbis-http2-17#section-8.1.2), header names should be lowercased. Currently all headers in Vapor's `HeaderKey` class are CamelCase.

Whilst Vapor does not currently support HTTP 2.0, if run behind Nginx or something that does, headers may be forwarded and will be invalid, so they should be made lowercase. In HTTP 1 header keys are case-insensitive so this won't introduce any issues.

(You could argue it is the responsibility of the proxy to lowercase everything but better to be safe!)

**Comment by LoganWright** [comment]
@0xTim theoretically, this wouldn't interfere w/ HTTP 1 spec, but I think I recall in the RFC seeing that while they _are_ case insensitive, we should treat them as camel cased in case there's bad parsers out there. I'm curious how this might affect that, and how we might make sure both systems are operating most efficiently.

**Comment by 0xTim** [comment]
Hmm I can see this becoming a mess! Looks like there are some servers that don't respect the specs and IE 11 doesn't like it too much if you start sending it mixed case headers..... But then HTTP should **only** be lowercase
¯\_(ツ)_/¯

**Comment by LoganWright** [comment]
I think for now, since Vapor doesn't support HTTP2.0 natively, and the 1.0 spec states that we should follow camel case conventions, we're going to leave this to the proxy.

Let's revisit when we ultimately introduce native HTTP 2.0 support.
