### ISSUE TITLE
[SMTP.SMTPClientError: invalidGreeting(code: -1, greeting: "")]

### ISSUE THREAD

**Issue by leonidas-o** [vapor/engine#138]
# Bugs

## Introduction

in V1 it was working with:

```swift
let client = try SMTPClient<TCPClientStream>.init(host: host, port: port, securityLayer: SecurityLayer.tls(nil))
try client.send(email, using: credentials)
```

In V2 I'm trying to send a Mail over SMTP using smpt.zoho.com.

Got the credentials and client conf in a smtpzoho.json file:
```json
{
        "client": {
        "scheme": "smtps",
        "host": "smtp.zoho.eu",
        "port": 465
}
```

## Code

```swift
        let credentials = SMTPCredentials(user: user, pass: pass)
        let from = EmailAddress(name: name, address: emailAddress)
        let to = EmailAddress(name: name, address: emailAddress)
        let emailBody = EmailBody(content: "\(nameRequest) - \(emailRequest) : \(messageRequest)")
        
        let email = Email(from: from,
                          to: to,
                          subject: "Contact form \(name)",
                          body: emailBody)
        
        
        let portConverted = Port(port)
                
        let mailer = SMTPMailer.init(scheme: scheme, hostname: host, port: portConverted, credentials: credentials)
        try mailer.send(email)
```

Mostly the last two lines have changed, and now a scheme has to be provided. I've tried with several schemes like "ssl", "smtps", ssmtp", "http", "https" but all give me the same error:
```sh
[SMTP.SMTPClientError: invalidGreeting(code: -1, greeting: "")]
Conform 'SMTP.SMTPClientError' to Debugging.Debuggable to provide more debug information.
```

**Comment by LoganWright** [comment]
@leonidas-o I've been poking at this one for a while, and I'm pretty stuck, have you looked into the 3rd party mailer party in the interim?

**Comment by leonidas-o** [comment]
no, haven't looked really for a 3rd party solution. I think I saw just one, but it was outdated and not released for v2. Also I thought this would not be something bigger, as it was already working in V1.

**Comment by Andrewangeta** [comment]
Any progress on this one? It's kinda weird that it worked in V1 excellently. Most of the actual code from smtp didn't change much just moved around. I don't understand why or how it broke.

**Comment by leonidas-o** [comment]
While I was stepping through the code, I encountered that you get the correct replyCode in SMTPClient+Reply.swift `acceptReplyLine()` method when using:

{
        "client": {
        "scheme": "smtp",
        "host": "smtp.zoho.eu",
        "port": 587
}

So with this you get a valid greeting. Nevertheless there is still an issue. 

It looks like everything seems to be ok until `SMTPClient+Send.swift` 
```
try transmit(line: "MAIL FROM: <\(email.from.address)>", expectingReplyCode: 250)
```
One step further into `SMTPClient+Transmit.swift`:
```
    internal func transmit(line: String, terminating: Bool = true, expectingReplyCode: Int) throws {
        try transmit(line: line, terminating: terminating)
        let (code, replies) = try acceptReply()
        guard code == expectingReplyCode else {
            throw SMTPClientError.unexpectedReply(expected: expectingReplyCode, got: code, replies: replies, initiator: line)
        }
    }
```
At `guard code == expectingReplyCode else {` 250 is expected, but got 530, so it throws.
```
[SMTP.SMTPClientError: unexpectedReply(expected: 250, got: 530, replies: ["Must issue a STARTTLS command first."], initiator: "MAIL FROM: <foo@foobar.com>")]
Conform 'SMTP.SMTPClientError' to Debugging.Debuggable to provide more debug information.

**Comment by Andrewangeta** [comment]
Maybe there needs to be another authorization method other than login and plain?

**Comment by leonidas-o** [comment]
I don't think that this would solve the problem. When setting a breakpoint:
```
    internal func authorize(extensions: [EHLOExtension], using credentials: SMTPCredentials) throws {
        if let auth = extensions.authExtension {
            if auth.params.contains(where: { $0.equals(caseInsensitive: "LOGIN") }) {
                try authorize(method: .login, using: credentials)
            } else if auth.params.contains(where: { $0.equals(caseInsensitive: "PLAIN") }) {
                try authorize(method: .plain, using: credentials)
            } else {
                throw SMTPClientError.unsupportedAuth(supportedByServer: auth.params,
                                                      supportedBySMTP: SMTPAuthMethod.all)
            }
        } else {
            // no authorization required -- should we throw here?
            // I'm pretty sure classic SMTP is no login, aka, supah safe
            return
        }
    }
```
I'm getting into the else clause as extensions do not contain `authExtension`:
<img width="283" alt="screen shot 2017-07-18 at 16 37 17" src="https://user-images.githubusercontent.com/2997492/28322898-9ddd7ad8-6bd7-11e7-9cd1-1d05fb2487fa.png">

**Comment by Andrewangeta** [comment]
So it's missing the extensions. 
http://www.samlogic.net/articles/smtp-commands-reference-auth.htm

**Comment by bottlehall** [comment]
The bug 1108 referenced above  was closed... after referencing this bug! A deadly embrace. Is anybody working on it?

I get this error too, but it is after a timeout of at least 1 minute. It happens for gmail and my own domain mail. It also doesn't matter if the authorisation credentials are correct or wrong, it behaves the same. As far as I can see, the vapor end isn't sending anything after the socket is opened and eventually the remote end drops it. I could be wrong.

**Comment by bottlehall** [comment]
I've set up a test server with postfix running on it. Everything works fine with unencrypted SMTP. Not much use in practice though. Anyone else working on this problem?

**Comment by tanner0101** [comment]
We're deprecating SMTP support with Vapor 2. This will no longer be included in Vapor 3 (due to the complexity to get it working properly). I'm really sorry about the inconvenience this caused in Vapor 2. We should have had that tested better before release.
