### ISSUE TITLE
http client sending body twice

### ISSUE THREAD

**Issue by RobertTheProfessional** [vapor/engine#139]
# Bug 

## Introduction
When sending a PUT request to a Node.js REST service on my local machine that takes on average 700ms to 1s to resolve, the Vapor application fails the client request almost immediately before the request even touches the starting breakpoint of the Node.js route handler. I've only seen this issue occur when using the Vapor Engine 2.0.3 as the client framework; when the framework is switched to Foundation the error disappeared completely and the REST request would resolve normally.

I've tracked the issue down to a specific block of code in the `HTTP+Client.swift` file of the Vapor Engine 2.0.3 package. From what I can tell the stream sends the bytes to the Node.js REST service on line 69 of my screenshot below but attempts to read from the stream too quickly on line 88 despite the fact that my service hasn't completed its operation yet. As a result, the `read` constant is set to 0 and the response stream appears to be empty which triggers the guard to break the while loop; causing the empty Response object to throw the `StreamError.closed` error.

<img width="2032" alt="vapor http client request - no breakpoint blocking" src="https://cloud.githubusercontent.com/assets/1852571/26770914/a3cc3e8c-4988-11e7-9bc1-a1205087b781.png">

When a breakpoint is set on line 81 of the screenshot below and the client request is made, the breakpoint is hit and execution is blocked for roughly 2-3 seconds before I allow the program to continue execution. Given the brief pause, my Node.js service is able to complete it's operation and the stream can successfully read the response from my service. As a result the `read` constant is now set to 2048 instead and the Response object is successfully initialized.

<img width="2032" alt="vapor http client request - breakpoint blocking" src="https://cloud.githubusercontent.com/assets/1852571/26770957/e5583b6c-4988-11e7-88fe-bb667ee0ca84.png">

**Comment by tanner0101** [comment]
That's strange that your Node.js server is responding with an EOF signal. If `recv()` ever returns `0`, that means the stream has been closed normally and should not be read from again. This should only ever happen if `close()` is called on the FD from the sending end. Otherwise, `recv()` should block until data is ready. Does this happen for any of the other endpoints on your Node.js REST service or is it only for this one in particular?

**Comment by RobertTheProfessional** [comment]
Other endpoints on the Node.js service are able to resolve correctly, although they execute rather quickly so I'll try to insert a delay to see if the problem is repeatable. I'm not sure why the Node.js service is returning an EOF immediately before the first breakpoint of its business logic is hit. After a deeper look, I found the TCPReadableSocket implementation in the Socket 2.0.1 package, which appears to contain the libc `read()` call which causes the error.

As noted in the [libc read() manpages](http://www.manpages.info/macosx/read.2.html), 
> Upon reading end-of-file, zero is returned.

It's looking more like due to Node.js doing weird Node.js things 😛 on that particular response, the Vapor Client Engine bails out pretty quickly since it's being presented with what it believes to be an EOF from the server; not much of a fault on the Vapor side.

I'll have to look a little deeper into my Node service to see why it's behaving sporadically; but the thing that has me confused now is why the Foundation Client Engine works perfectly fine with the server and blocks until all the information is received.

**Comment by RobertTheProfessional** [comment]
Actually, I take it back for some reason instead of acknowledging 404s from the Node service, Vapor still throws the Transport.StreamError.Closed error

**Comment by tanner0101** [comment]
Thanks for digging into this! That's definitely a bug on our end that you correctly noted was introduced in https://github.com/vapor/engine/pull/137. I've created a PR to fix this here https://github.com/vapor/engine/issues/140.

**Comment by tanner0101** [comment]
@RobertTheProfessional can you verify for me that the changes in #140 fix the issue you are having?

**Comment by RobertTheProfessional** [comment]
After cleaning the `.build` folder, fetching a fresh version of Vapor Engine 2.0.3 and implementing the changes in your commit; I can confirm that the bug has been resolved.

**Comment by tanner0101** [comment]
Thanks again @RobertTheProfessional. I'll merge this bug fix as a patch release (2.0.4)
