### ISSUE TITLE
unsupportedURICharacter(60) error when running on Linux

### ISSUE THREAD

**Issue by gmosx** [vapor/engine#142]
I have a simple websocket client that uses Vapor Engine. The client connects to a `wss://` endpoint.
The client works fine on macOS.

However, when I compile and run it on Ubuntu, it doesn't connect and I get the following cryptic error:

`unsupportedURICharacter(60)`

Any ideas what might be the problem?

**Comment by LoganWright** [comment]
@gmosx no idea off the top of my head, any more info or context about what exactly is going on here or a way to possibly recreate it? If we could make a unit test to find it, that would definitely help us start narrowing down.

**Comment by tanner0101** [comment]
Feel free to re-open when we get more info.
