### ISSUE TITLE
URI Parser doesn't allow hostname containing _

### ISSUE THREAD

**Issue by valeriomazzeo** [vapor/engine#174]
I am having issues in connecting to a server with an hostname containing `_`:

`try EngineClientFactory().get("http://test_server-02:8080/my/path")`

The problem is in the `URIParser` class, which crops the hostname to `test` rather than `test_server-02`.

**Comment by vzsg** [comment]
Here's what I know so far:
1. In theory, underscores are invalid in hostnames. Yet in practice, everyone (starting from browsers, frameworks, etc.) bent the knee and started being lax about the validation.
1. The `http_parser_parse_url` C function in CHTTP has a strict and a lax mode.
1. In the default strict mode, underscore is considered invalid and the above described behavior happens. If strict mode is disabled, the URL is parsed correctly.
1. Strict mode can be disabled using a compile time flag as seen [here](https://github.com/vapor/engine/blob/master/Sources/CHTTP/include/http_parser.h#L49-L54). _I don't remember how to override it with SPM, but monkey-patching the 1 to 0 allowed me to test the lax mode._
1. And the URL is correctly parsed that way.

**Comment by tanner0101** [comment]
You should be able to pass `-Xswiftc -DHTTP_PARSER_STRICT=0` using SPM. 

Maybe it's worth having this default to lax mode in Vapor 3's HTTP parser? 

\cc @Joannis we should test if that has any performance implications.

**Comment by vzsg** [comment]
As the CHTTP source is part of this repo, perhaps it would be easier to just flip the define here.

**Comment by tanner0101** [comment]
Are there any arguments against disabling strict mode?

My concerns are:
- potential security vulnerabilities this opens up
- performance concerns (CHTTP presumably optimizes the happy-path most)

IMO the unknowns here outweigh the benefit of supporting malformed URLs as I've yet to encounter one.

**Comment by tanner0101** [comment]
Closing this one in favor of the compiler flags mentioned here: https://github.com/vapor/engine/issues/174#issuecomment-344434949
