### ISSUE TITLE
Engine 3 URI not working correctly

### ISSUE THREAD

**Issue by 0xTim** [vapor/engine#190]
Hitting an issue with the URI, unsure if it is the description or initialiser that is causing the problem. Basically create a URI with:

```swift
let uri = URI(scheme: "https", hostname: "geeks.brokenhands.io", path: "/blog/")
```
If I then get `uri.description` it returns `httpsgeeks://` which is obviously wrong!

**Comment by Joannis** [comment]
Fixed in #182
