### ISSUE TITLE
[beta] HTTPSerializerStream.swift @ compile error

### ISSUE THREAD

**Issue by fwx** [vapor/engine#193]
Trying to establish Vapor 3 (upgrading from 2.x), already spent like 2 hours trying to fix random things (probably the problem is in my hands), but stuck on this one:

```
HTTPSerializerStream.swift:119:28: error: contextual closure type '(HTTPChunkEncodingStream.Output, ConnectionContext) -> ()' (aka '(UnsafeBufferPointer<UInt8>, ConnectionContext) -> ()') expects 2 arguments, but 1 was used in closure body
            stream.drain { req in
```
```
Sources/HTTP/Serializer/HTTPSerializerStream.swift:136:28: error: contextual closure type '(ByteBuffer, ConnectionContext) -> ()' (aka '(UnsafeBufferPointer<UInt8>, ConnectionContext) -> ()') expects 2 arguments, but 1 was used in closure body
```

Any ideas on this?
Sorry for not filling info as guidelines say.

**Environment**:
Apple Swift version 4.0.3 (swiftlang-900.0.74.1 clang-900.0.39.2)
Target: x86_64-apple-macosx10.9
Vapor Toolbox: 3.1.2

**Comment by fwx** [comment]
added second arg, still an error:
![2018-01-13 17 51 42](https://user-images.githubusercontent.com/7344370/34904113-7878ffd4-f88a-11e7-8b29-6e7924c115c5.png)

**Comment by fwx** [comment]
I guess that it is related to reactive http parser and the class is not finished yet, so clossing the issue.

**Comment by vzsg** [comment]
I'm also seeing this, so let's keep the issue open until the big PR lands.

**Comment by Joannis** [comment]
Should be fixed now
