### ISSUE TITLE
Route Parameter Collisions 

### ISSUE THREAD

**Issue by calebkleveter** [vapor/engine#206]
If I have two routes that have the same path, other then the route parameters, only the first route works, even if they use different types. Example; if I have two routes:

    Gets a user by their username
    GET /users/:string

    Gets a user by their ID
    GET /users/:int

If I try to access the second route, I will get an error because the request tries to convert a `String` to an `Int`, and you get an error looking like this:

    Oops: Invalid parameter type. Expected Int got [115, 116, 114, 105, 110, 103]

I think it would make more sense if we look for a route that matches the type passed in, and better yet, the amount of parameters passed in (so we could have a route that takes in 1 `String` and a second route that takes in 2).

You can test this issue by spinning up [this project](https://github.com/vapor-community/PackageCatalogAPI), and un-commenting line 45 in `PackageController.swift`. Then make a call to the `GET /packages/:int` route. You'll get a parameter type failure.

**Comment by twof** [comment]
https://github.com/vapor/vapor/issues/1427
Related

**Comment by tanner0101** [comment]
The logic to do this (and potentially the performance implications) are non-trivial. We should make sure this is something people really want/need before we consider adding complexity to the core router.

**Comment by Joannis** [comment]
I'm not for this change/addition. If you'd like to support both `Int` and `String` parameters it makes more sense to me to make the `User` model, in this case, implement it's own custom parameter resolving. Like attempting `Int` first and falling back on `String`

**Comment by twof** [comment]
"Like attempting Int first and falling back on String"
I agree that a `User` model would be better, but why is this not the default?

**Comment by Joannis** [comment]
Do you mean decoding both as a String and an ID by default? The default implementation doesn't know which fields are good to be parameterized. For all the implementation knows, the `age`, `email` or `permissions` fields are equally relevant as `username`

**Comment by tanner0101** [comment]
Closing this one due to inactivity.
