### ISSUE TITLE
Error: Missing required module 'CSQLite'

### ISSUE THREAD

**Issue by asterikx** [vapor/engine#207]
Hi, I have built a Vapor server application, and I want to wrap that application into a Cocoa app (to start/stop the server, basic monitoring visualization, etc...)
I have followed the approach described [here](http://eon.codes/blog/2017/02/05/Xcode-and-spm/). It works except for `CSQLite`:
```
Missing required module 'CSQLite'
```
Apparently it's because `CSQLite.framework` does not contain any modules (no `Modules/` folder): 
 
![screenshot 2018-01-23 00 53 04](https://user-images.githubusercontent.com/16797665/35250825-cfa50f3c-ffd8-11e7-9329-f7f2f98bc061.png)

Compared to other bundles, e.g. `SQLite.framework`:

![screenshot 2018-01-23 00 52 53](https://user-images.githubusercontent.com/16797665/35250820-ccc94634-ffd8-11e7-8632-1d244bd5ae98.png)

Probably the same issue also exists for `CHTTP`. 

I don't know if it's a bug or expected behavior. Any help would be greatly appreciated.

Thanks!

**Comment by vzsg** [comment]
CSQLite and CHTTP are not Swift modules, but compiled from C sources. That might explain why the Modules folder is missing (and that's not a problem in itself).

Whether this approach should work in the first place, or how it could be fixed is beyond me though.

**Comment by tanner0101** [comment]
Try building w/ this flag: https://github.com/vapor/fluent/blob/master/Package.swift#L26.

But as @vzsg said, this probably won't work. Even if you get it to compile, I don't think using POSIX sockets on iOS works or is a good idea.

**Comment by jalakoo** [comment]
I'm sorry, I'm not following the suggestion above.  The link goes to the `fluent` package which is one of the `fluent-mysql` dependencies.  Is there a special `vapor update` flag we're suppose to use that does something specific with that package?

**Comment by twof** [comment]
This problem is typically solved by cleaning xcode (cmd+shift+k) and then building again

**Comment by jalakoo** [comment]
So the issue for me was I still had some references to FluentSQLite after replacing the template code to use FluentMySQL. Solution posted in the Slack channel by 0xtim.

**Comment by vzsg** [comment]
Note that the suggestion was made in January, when the master branch contained sources for Vapor 2. Since then, it was replaced by the in-development Vapor 3, so the link is no longer relevant.

**Comment by tylermilner** [comment]
@twof's suggestion fixed this error for me. Simply cleaning the project and rebuilding was all that's required.
