### ISSUE TITLE
droplet.client.post not showing in Charles

### ISSUE THREAD

**Issue by itouch2** [vapor/engine#216]
I use ```droplet.client.post``` to fetch remote data, and it works. However, the connection doesn't show in Charles. Should I configure the proxy or something?

**Comment by vzsg** [comment]
Yes, you'll have to configure Charles as the HTTP proxy (IIRC it's `localhost:8888`), as the low-level networking Vapor uses does not care much for the system proxy settings.

Try creating `Config/client.json` with the following content:

```json
{
    "proxy": {
        "hostname": "localhost",
        "port": 8888
    }
}
```
