### ISSUE TITLE
Can't decode array from request content

### ISSUE THREAD

**Issue by niksauer** [vapor/engine#233]
* Vapor Version: 3
* OS: macOS 
* OS Version: 10.13.12 (High Sierra)
* Vapor Toolbox Version: 3.1.3

### Expected Behavior
Array<Type> is decoded from request body. 

### Current Behavior
Application crashes with error: 
```
Fatal error: file /Users/nik/Documents/Developer/Swift/RoadChatAPI/.build/checkouts/engine.git-3311994267206676365/Sources/FormURLEncoded/ArrayKey.swift, line 9
[1]    24002 illegal hardware instruction  swift run Run serve --hostname 0.0.0.0
```

### How to Reproduce
`_ = try req.content.get([Int].self, at: parameter.name).await(on: req)`

### How to Fix
Properly implement Protocol `CodingKey` for ArrayKey. Currently:

```swift
struct ArrayKey {
    let index: Int
    init(_ index: Int) {
        self.index = index
    }
}

extension ArrayKey: CodingKey {
    var stringValue: String { fatalError() }
    init?(stringValue: String) { fatalError() }
    var intValue: Int? { return index }
    init?(intValue: Int) { fatalError() }
}
```

Possibly (but invalid due to duplicate conformance and only partly implementation each time):
```swift
struct ArrayKey<T> {
    let index: T
    init(_ index: T) {
        self.index = index
    }
}

extension ArrayKey: CodingKey where T == Int {
    var intValue: Int? { return index }
    init?(intValue: Int) { self.index = intValue }
}

extension ArrayKey: CodingKey where T == String {
    var stringValue: String { return index }
    init?(stringValue: String) { self.index = stringValue }
}
```

**Comment by tanner0101** [comment]
Can you provide the request data you used to cause this error? I attempted to recreate it here: https://github.com/vapor/engine/pull/236

But I'm not seeing a failure.

**Comment by niksauer** [comment]
Sorry, this has been an error on my part. Postman is not able to encode the data properly. It works using CURL. **But** the `fatal error` still hits me if the parameter is not supplied. Can this be changed to a throwing method?

**Comment by tanner0101** [comment]
@niksauer can you specify which one this is referring to:
>  the parameter

If you could provide code for the entire route + the exact code you run in the terminal to recreate, that would be super helpful!

The `fatalError`s are there specifically because those methods should never be called. There must be something else going wrong.

**Comment by niksauer** [comment]
```
struct ConversationRequest: Codable {
    let title: String
    let participants: [Int]
}
```

```
protocol Payload {
    associatedtype RequestType: Validatable, OptionallyValidatable
    typealias Parameter = (name: BasicKeyRepresentable, type: Decodable)
    static var requiredParameters: [Parameter] { get }
    static var optionalParameters: [Parameter] { get }
}

extension Payload {    
    private static func findMissingParameters(in req: Request, required parameters: [Parameter]) -> [Parameter] {
        var missingParameters = [Parameter]()
        
        for parameter in parameters {
            do {
                switch parameter.type {
                case is [Any]:
                    // fatalError is thrown here
                    _ = try req.content.get([String].self, at: parameter.name).await(on: req)
                default:
                    _ = try req.content.get(String.self, at: parameter.name).await(on: req)
                }
            } catch {
                missingParameters.append(parameter)
            }
        }

        return missingParameters
    }
}
```

I was referring to the parameter `participants`. Assuming that both are present, `findMissingParameters(in:required:)` will return an empty array, since it was able to decode both a `String` and `[String]` from the request:

```
curl -X POST http://localhost:8080/chat -H "Authorization: Bearer XXX" -d "title=CryptoBros" -d "participants[]=1"
```

Contrarily, it will crash with the following error if `participants`is not supplied, even though this decoding attempt is wrapped in a `do-catch`. Also for any other non-array parameter, the parameter will be added to the `missingParameters` set if not present in the request:

```
curl -X POST http://localhost:8080/chat -H "Authorization: Bearer CC2921EC-99E5-438D-ABC5-4885DD01906A" -d "title=CryptoBros"
curl: (52) Empty reply from server
```

```
Fatal error: file /Users/nik/Documents/Developer/Swift/RoadChatAPI/.build/checkouts/engine.git-3311994267206676365/Sources/FormURLEncoded/ArrayKey.swift, line 9
[1]    23202 illegal hardware instruction
```
