### ISSUE TITLE
Satisfy HTTP/1.1 requirement of 'Host' header  in client requests in HTTPClient

### ISSUE THREAD

**Issue by givip** [vapor/engine#268]
Version: 3.0.0-rc.2.3.1

I founded a bug, when some virtual hosted websites responds with 400 http code error while interacted via HTTPClient  (NIO implementation).
After some investigation I've figured out, that _Host_ header is required [https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.23](url)

Also, about header _Content-Length_ discussion needed, because in my opinion It's not always  needed [https://stackoverflow.com/a/8540951](url)
[https://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html#sec4.4](url)

And while initializing HTTPRequest _Content-Length_ will be fulfilled in any case.

**Comment by tanner0101** [comment]
Merged the PR, thanks!
