### ISSUE TITLE
Tests fail when ran in a different timezone

### ISSUE THREAD

**Issue by czechboy0** [vapor/engine#30]
I'm based in the Czech Republic (UTC+2 now in the summer) and I have Engine tests failing because the date formatters are using specific timestamps, which translate to different dates here. Specifically those are:

Failing because of timezone:
```swift
SMTPDateTests.testSMTPDate()
```

Because of getting different response to `google.com`:

```swift
SockStreamTests.testTCPInternetSocket()
SockStreamTests.testFoundationStream()
```

I get: `HTTP/1.0 302 Found\r\nCache-Control: private\r\nContent-Type: text/html; charset=UTF-8\r\nLocation: http://www.google.cz/?gfe_rd=cr&ei=WYG8V_CHBtDR8geml7zYAg\r\nContent-Length: 258\r\nDate: Tue, 23 Aug 2016 17:01:13 GMT\r\n\r\n<HTML><HEAD><meta http-equiv=\"content-type\" content=\"text/html;charset=utf-8\">\n<TITLE>302 Moved</TITLE></HEAD><BODY>\n<H1>302 Moved</H1>\nThe document has moved\n<A HREF=\"http://www.google.cz/?gfe_rd=cr&amp;ei=WYG8V_CHBtDR8geml7zYAg\">here</A>.\r\n</BODY></HTML>\r\n`

We just need to find a way to ensure the timezone tests work around the world (probably by setting the timezone in tests to a set one), and pick a different URL than `google.com` which responds the same way to all locations.

**Comment by LoganWright** [comment]
Sounds like moving to http://httpbin.org/ will fix, let's integrate this before official release for international contributors.

**Comment by czechboy0** [comment]
Yeah, that'll fix the live requests. We also need to fix the timezone failure, which could be achieved by setting a specific time zone on the formatter.

**Comment by tannernelson** [comment]
We've mostly moved to HTTP bin now.
