### ISSUE TITLE
Fix Github project title

### ISSUE THREAD

**Issue by pkese** [vapor/engine#369]
Without looking at the code, it is unclear if this project is a HTTP server or client (I was searching for client)

:rocket: Non-blocking, event-driven HTTP built on Swift NIO.  
->  
:rocket: Non-blocking, event-driven HTTP **server** built on Swift NIO.

**Comment by vzsg** [comment]
What would you name it then, considering it has both a client and a server part implemented?

**Comment by pkese** [comment]
Facepalm - I didn't notice it had client as well.
