### ISSUE TITLE
fatal error: Error raised at top level: SMTP.SMTPClientError.invalidPassword

### ISSUE THREAD

**Issue by b20160** [vapor/engine#50]
Currently the user is required to change their settings for their Gmail account to "Allow for less secure apps"

fatal error: Error raised at top level: SMTP.SMTPClientError.invalidPassword(534, "5.7.14 <https://accounts.google.com/signin/continue?sarp=1&scc=1&plt=AKgnsbtW"): file /Users/buildnode/jenkins/workspace/oss-swift-package-osx/swift/stdlib/public/core/ErrorType.swift, line 160

**Comment by LoganWright** [comment]
@b20160 Thanks for the reminder, I'll put that in the docs 👍

**Comment by tannernelson** [comment]
This has been added to the example.
