### ISSUE TITLE
Websocket: Response Header may differ depending on the API address

### ISSUE THREAD

**Issue by Narsail** [vapor/engine#63]
While i tried to connect to the Websocket of the Poloniex https://poloniex.com/support/api/ i encountered response properties with a mix of lowercase/uppercase styles. The WebSocket+Client.swift implementation checks against "upgrade" with "websocket" while Poloniex responded with "WebSocket". 

To solve this problem i lowercased the response properties in the header check.
Pullrequest: #61

**Comment by tannernelson** [comment]
This has been merged, thanks!
