### ISSUE TITLE
Update to eliminate deprecation warning

### ISSUE THREAD

**Issue by rcritz** [vapor/engine#65]
I'm just trying Vapor for the first time today. Xcode 8.1 (not that I think the version matters) pops a deprecation warning for line 27 of Transport/Streams/Socks+Stream.swift. For fear of stepping on someone's toes, I offer this issue here rather than submitting a pull request. Changing the line to read:

```
try setSendingTimeout(timeval(seconds: timeout))
```

fixes the problem. I'm happy to submit it as a PR if that helps, but again don't want to step on anyone's toes. Thanks!

**Comment by LoganWright** [comment]
@rcritz working on it now, we need to update TLS first so we can properly version this as 1.1.0..<2.2.0. Should hopefully be done today if CI works quickly.

**Comment by LoganWright** [comment]
https://github.com/vapor/engine/releases/tag/1.1.0
