### ISSUE TITLE
Server stalls if the GCD thread pool is exhausted

### ISSUE THREAD

**Issue by andreasley** [vapor/engine#66]
Grand Central Dispatch is spawning a limited amount of threads (my tests indicated `number of virtual CPU cores * 5`, but at minimum `64`).

Since `Server` responds to requests [on a GCD queue](https://github.com/vapor/engine/blob/1f95094ee470408309e98dd56b2251210d6a2a3d/Sources/HTTP/Models/Server/HTTP%2BServer.swift#L63), the server stalls if that pool is exhausted. New requests get queued but may wait for processing forever – for example if all threads are waiting for data on sockets that are not connected anymore (there is currently no read timeout set on server sockets).

When running behind nginx, this is irrelevant as long as the connection between nginx and Vapor is good.
When exposed directly, the server stalls within minutes or hours.

I think it's reasonable to only process 64 parallel requests; however, waiting on (potentially dead) sockets shouldn't happen in this queue. A read timeout on the socket would help, but not solve the problem.

In the end, the socket should be non-blocking. Unfortunately, I currently don't see an easy way to get there.

**Comment by LoganWright** [comment]
@andreasley I think this is an important discussion to bring up, particularly in the Swift server group. Are you a part of that? I think you'd be an amazing addition to the sockets/networking team.

My suggestion is that we see what some of the non-blocking plans are for that and in the interim implement read timeouts to alleviate the situation.

**Comment by andreasley** [comment]
@LoganWright Thanks. Not sure if I'd be a good fit for the Swift server work group (time constraints), but I'll definitely keep an eye on it and would love to help if I can.

> My suggestion is that we see what some of the non-blocking plans are for that and in the interim implement read timeouts to alleviate the situation.

That's reasonable. 
Currently, a write timeout of 30 seconds is set [here](https://github.com/vapor/engine/blob/e455637895cbcb81adc65c64f93d13bdb834eb51/Sources/Transport/Streams/Socks%2BStream.swift#L28) and [here](https://github.com/vapor/engine/blob/e455637895cbcb81adc65c64f93d13bdb834eb51/Sources/Transport/Streams/Socks%2BStream.swift#L135) in `Socks+Stream.swift`. I think a read timeout of the same duration would be sensible.

**Comment by LoganWright** [comment]
@andreasley I agree, and seriously, thanks for all of your contributions across the board. It's been very high quality and we really appreciate it.

**Comment by LoganWright** [comment]
@andreasley merged in now, let me know if you still see this on latest release.

**Comment by andreasley** [comment]
@LoganWright Unfortunately, the read timeout has a side effect in the form of the following error that is thrown when a connection times out (can be easily reproduced by loading any page from a browser that requests `keep-alive` and wait 30 seconds):

`Server error: dispatch(Transport.StreamError.receive("There was a problem while receiving data.", Socket failed with code 35 ("Resource deadlock avoided") [readFailed] "Unknown error"))`

**Comment by andreasley** [comment]
@LoganWright I have a prototype of Vapor with nonblocking sockets running (using [DispatchSource](https://developer.apple.com/reference/dispatch/dispatchsource)). However, I need some time to make sure everything is working as expected and add documentation. I'll create a PR when this is ready.

I've looked at various options, but going with `libdispatch` seemed to be the logical choice since Vapor is already using it and it works on both macOS and Linux.

**Comment by LoganWright** [comment]
@andreasley libDispatch is definitely the way to go, I can't wait to see what you've got!

**Comment by andreasley** [comment]
@LoganWright Here are the promised Pull Requests:

**Socks:** https://github.com/vapor/socks/pull/86
* Adds the ability to "watch" sockets, which also makes them nonblocking
(can be merged without any side effects)

**Engine:** https://github.com/vapor/engine/pull/71 (depends on PR for Socks)
* Makes `Stream` watchable
* Makes `Server` use `startWatching` on Streams instead of using loops

**Vapor:** https://github.com/vapor/vapor/pull/690 (depends on the PR for Engine)(depends on the PR for Engine)
* Makes Droplets retain a list of bootedServers, since they would be released otherwise
* Simplifies `bootServer`

All things considered, it's only a small amount of code. The tricky part was finding a good place for it.

Is backwards compatibility required (e.g. if someone wants to run a newer Vapor with an older engine)? If so, I could split away the new code instead of replacing existing functions.

## Impact on throughput

Throughput is almost identical. Depending on the circumstances (like number of connections), the nonblocking variant is slightly faster oder slower, but always very close.

nonblocking:
```
$ wrk -d 10 -t 4 -c 16 http://0.0.0.0:8001
Running 10s test @ http://0.0.0.0:8001
  4 threads and 16 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     0.95ms  117.48us   4.85ms   70.58%
    Req/Sec     4.20k    41.39     4.30k    73.76%
  168712 requests in 10.10s, 13.68MB read
Requests/sec:  16703.92
Transfer/sec:      1.35MB
```

blocking:
```
$ wrk -d 10 -t 4 -c 16 http://0.0.0.0:8001
Running 10s test @ http://0.0.0.0:8001
  4 threads and 16 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     0.98ms  191.03us   7.43ms   77.33%
    Req/Sec     4.07k    98.23     4.37k    74.50%
  163564 requests in 10.10s, 13.26MB read
Requests/sec:  16194.09
Transfer/sec:      1.31MB
```

## Impact on concurrency

Concurrency is massively improved. While the blocking variant can be stalled by simply opening 100 or so connections, the nonblocking one will continue to respond as long as the OS has sockets available.

**Comment by tannernelson** [comment]
@andreasley this PR is looking awesome.

I ran into an error while testing:

![screen shot 2016-11-07 at 2 28 51 pm](https://cloud.githubusercontent.com/assets/1342803/20072484/98e718fc-a4f6-11e6-87e7-9780f47afb64.png)

I was able to fix it by commenting out the `.main.sync` call.

This code works without crashing:

```swift
        do {
            try runCommands(servers: servers)
            // DispatchQueue.main.sync {
                RunLoop.current.run()
            // }
            exit(0)
        } catch CommandError.general(let error) {
```

Any idea why that is happening?

**Comment by tannernelson** [comment]
Found another error:

```
Linking ./.build/release/App
duplicate symbol __TMRbBp in:
    /Users/tanner/Desktop/NonBlocking/.build/release/Fluent.build/SQL/GeneralSQLSerializer.swift.o
    /Users/tanner/Desktop/NonBlocking/.build/release/Vapor.build/Serve/Droplet+BootServers.swift.o
ld: 1 duplicate symbol for architecture x86_64
```

Fixed by replacing the closure being passed by name to calling it inside of a closure.

`Droplet+BootServers.swiftL38`
```swift
            errors: { e in 
                self.serverErrors(error: e) 
            }
```

**Comment by tannernelson** [comment]
Benchmarks passing. Looks like speed is about the same.

Non blocking.
```sh
Agatha:~ tanner$ wrk -t 4 -c 128 -d 10 http://0.0.0.0:8080/plaintext
Running 10s test @ http://0.0.0.0:8080/plaintext
  4 threads and 128 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     3.70ms    5.37ms 189.03ms   99.44%
    Req/Sec     9.46k   231.63    10.69k    82.25%
  376654 requests in 10.00s, 33.41MB read
Requests/sec:  37662.35
Transfer/sec:      3.34MB
```

Blocking.
```
Agatha:~ tanner$ wrk -t 4 -c 128 -d 10 http://0.0.0.0:8080/plaintext
Running 10s test @ http://0.0.0.0:8080/plaintext
  4 threads and 128 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     2.56ms   12.71ms 143.98ms   96.43%
    Req/Sec     9.62k     3.39k   35.40k    79.55%
  383883 requests in 10.10s, 34.05MB read
  Socket errors: connect 0, read 0, write 0, timeout 6
Requests/sec:  38006.81
Transfer/sec:      3.37MB
Agatha:~ tanner$ 
```

**Comment by tannernelson** [comment]
Seems that non blocking uses less CPU and Memory.

## Blocking

![screen shot 2016-11-07 at 3 13 35 pm](https://cloud.githubusercontent.com/assets/1342803/20074227/68553050-a4fd-11e6-805e-f602919318e0.png)

![screen shot 2016-11-07 at 3 13 42 pm](https://cloud.githubusercontent.com/assets/1342803/20074232/6b379c5e-a4fd-11e6-9887-24af5437ccc9.png)

## Non Blocking

![screen shot 2016-11-07 at 3 17 16 pm](https://cloud.githubusercontent.com/assets/1342803/20074243/7064e0a6-a4fd-11e6-8e25-4b47b785b2c8.png)
![screen shot 2016-11-07 at 3 17 14 pm](https://cloud.githubusercontent.com/assets/1342803/20074246/7243741e-a4fd-11e6-99db-6d096d7d354f.png)

**Comment by andreasley** [comment]
@tannernelson 

> I was able to fix it by commenting out the `.main.sync` call.

Weird. I'm not sure why this is happening. I only added `.main.sync` after testing failed and I noticed that some tests in `Vapor` execute `drop.run()` on a background queue, so this made the tests work again. Interestingly, the version I pushed works without errors on my system (El Capitan 10.11.6 (15G1108)). This is the code I used for my droplet: 

```swift
import Vapor

let droplet = Droplet()
droplet.middleware = []
droplet.get("/") { request in
    return "Hello"
}
droplet.run(servers: ["default":("0.0.0.0", 8001, .none)])
```

From the benchmark, it looks like you are using `engine` without `Vapor`. How exactly do you start the server? Maybe there's no `RunLoop.current` in your configuration.

We don't necessarily need a `RunLoop` and could just do this instead:

```swift
let group = DispatchGroup()
group.enter()
group.wait()
```

> Found another error:

The `duplicate symbol` error might be related to this Swift bug: https://bugs.swift.org/browse/SR-3081

**Comment by andreasley** [comment]
Fixed with the introduction of non-blocking behavior in [Vapor 1.2](https://github.com/vapor/vapor/releases/tag/1.2.0).
