### ISSUE TITLE
Gmail client is blocked by default

### ISSUE THREAD

**Issue by gmosx** [vapor/engine#75]
Emails using the Gmail client are blocked by default unless you enable access for less-secure apps in your Gmail account settings:

https://support.google.com/accounts/answer/6010255?hl=en-GB

**Comment by LoganWright** [comment]
@gmosx that should definitely be added to the comments on that function, I'll use that link. Thanks!

**Comment by BrettRToomey** [comment]
I'm pretty sure this was fixed a while ago. Closing. Feel free reopen.
