### ISSUE TITLE
WebSocket connection header case sensitivity

### ISSUE THREAD

**Issue by Obbut** [vapor/engine#76]
The [check for the 'Upgrade' value in the connection header](https://github.com/vapor/engine/blob/master/Sources/WebSockets/Request%2BWebSockets.swift#L18) is case sensitive. I don't know if this is according to the HTTP spec, but various nginx example configurations send the 'upgrade' value in lowercase.

I think this check should be made case insensitive.

**Comment by LoganWright** [comment]
@Obbut good call!

**Comment by kandelvijaya** [comment]
Lets close this. This one is already resolved.
